services:
  oko:
    build: .
    image: oko:latest
    container_name: oko
    restart: unless-stopped
    environment:
      - PUSHOVER_TOKEN=${PUSHOVER_TOKEN}
      - PUSHOVER_USER=${PUSHOVER_USER}
    command:
      - --plex-url=http://192.168.178.40:32400/identity
      - --qbit-url=http://192.168.178.40:8080
      - --interval-seconds=15
      # - --isp-ip=1.2.3.4